server:
  port: 14100

spring:
  application:
    name: metric-calculate
    version: @project.version@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.7.143:3307/rulecanvas2?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=PRC&allowMultiQueries=true&nullNamePatternMatchesAll=true&createDatabaseIfNotExist=true
    username: root
    password: MySQL!23

feign:
  magiccube-api:
    host: http://172.20.7.146:13611