server:
  port: 8888

spring:
  application:
    name: metric-calculate
    version: 1.0.0
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
  redis:
    host: 127.0.0.1
    port: 6379
    client-type: lettuce
    database: 1
#    password: Redis6379

# 端点控制配置
management:
  server:
    # 启用独立运维端口
    port: 50000
  endpoint:
    # 开启shutdown
    shutdown:
      enabled: true
    # 开启liveness和readiness端点
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      # 指定上下文路径，启用相应端点
      base-path: /actuator
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

#feign客户端url配置
feign:
  metric-config-api:
    host: http://localhost:${server.port}

knife4j:
  enable: true