server:
  port: 8888

spring:
  application:
    name: metric-calculate
    version: 1.0.0
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
  redis:
    host: 172.20.7.143
    port: 6379
    client-type: lettuce
    database: 1

feign:
  magiccube-api:
    host: http://localhost:8888