server:
  port: 8888

spring:
  application:
    name: metric-calculate
    version: 1.0.0
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
  redis:
    host: 127.0.0.1
    port: 6379
    client-type: lettuce
    database: 1
#    password: Redis6379

# 端点控制配置
management:
  server:
    port: 50000                         # 启用独立运维端口
  endpoint:                             # 开启shutdown和health端点
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        base-path: /actuator            # 指定上下文路径，启用相应端点
        include: health,shutdown

#feign客户端url配置
feign:
  metric-config-api:
    host: http://localhost:${server.port}

knife4j:
  enable: true