server:
  port: 8888

spring:
  application:
    name: metric-calculate
    version: 1.0.0
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher

feign:
  magiccube-api:
    host: http://172.20.7.146:13611