server:
  port: 8082

spring:
  application:
    name: metric-calculate-config
    version: '1.0.0'
    description: '指标配置服务'
  main:
    #允许循环依赖
    allow-circular-references: true
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ANT_PATH_MATCHER
  login-interceptor:
    exclude-path-list:
      - '/error'
      - '/doc.html/**'
      - '/webjars/**'
      - '/favicon.ico'
      - '/v3/api-docs/**'

  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/metric_calculate_config?characterEncoding=utf-8
    username: root
    password: root
  data:
    #redis相关配置
    redis:
      client-type: lettuce
      host: 172.20.7.106
      port: 16379
      database: 2
      password: Redis6379

  #jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_EMPTY
    time-zone: GMT+8

mybatis-flex:
  global-config:
    # 设置relation注解递归查询深度
    defaultRelationQueryDepth: 10
  mapper-locations:
    - classpath*:/mapper/*Mapper.xml

# 端点控制配置
management:
#  server:
#    # 启用独立运维端口
#    port: 50001
  endpoint:
    # 开启shutdown
    shutdown:
      enabled: true
    # 开启liveness和readiness端点
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      # 指定上下文路径，启用相应端点
      base-path: /actuator
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: 'com.yanggu.metric_calculate.config.controller'

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
